namespace Domain.Enums
{
    public enum Specializations
    {
        Dentist,
        GeneralPractitioner,
        Cardiologist,
        Dermatologist,
        Neurologist,
        Psychiatrist,
        OrthopedicSurgeon,
        Pediatrician,
        Gynecologist,
        Ophthalmologist,
        ENT_Specialist,
        Urologist,
        Radiologist,
        Oncologist,
        Endocrinologist,
        Gastroenterologist,
        Pulmonologist,
        Rheumatologist,
        Anesthesiologist,
        PlasticSurgeon,
        Nephrologist,
        Pathologist,
        Hematologist,
        Allergist,
        Immunologist,
        InfectiousDiseaseSpecialist,
        Geriatrician,
        SportsMedicineSpecialist,
        CriticalCareSpecialist,
        EmergencyMedicineSpecialist,
        FamilyPhysician,
        OccupationalTherapist,
        Physiotherapist,
        Dietitian,
        Chiropractor
    }

}
